; Template: Class Generator
className := "{{CLASS_NAME}}"
prop1 := "{{PROP1}}"
prop2 := "{{PROP2}}"
prop3 := "{{PROP3}}"

code := "#Requires AutoHotkey v2.0`n"
code .= "`n"
code .= "class " . className . " {`n"
code .= "    __New(" . prop1 . ", " . prop2 . ", " . prop3 . ") {`n"
code .= "        this." . prop1 . " := " . prop1 . "`n"
code .= "        this." . prop2 . " := " . prop2 . "`n"
code .= "        this." . prop3 . " := " . prop3 . "`n"
code .= "    }`n"
code .= "`n"
code .= "    ToString() {`n"
code .= "        return `"" . className . " {```n`"`n"
code .= "             . `"  " . prop1 . ": `" . this." . prop1 . " . `"```n`"`n"
code .= "             . `"  " . prop2 . ": `" . this." . prop2 . " . `"```n`"`n"
code .= "             . `"  " . prop3 . ": `" . this." . prop3 . " . `"```n`"`n"
code .= "             . `"}`"`n"
code .= "    }`n"
code .= "}`n"

FileAppend code, "*"
